spring:
   cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/12app/spring-cloud-event-sourcing-config.git
          username: "mhari.tech"    
          password: "09g81a0505"