spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
    client:
      client-id: acme
  enable-csrf: false
---
spring:
  profiles: development
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://localhost:3306/login_db
        username: root
        password: welcome_123!
        driver-class-name: com.mysql.jdbc.Driver
        initialize: false

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
  enable-csrf: false
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://localhost:3306/login_db
        username: root
        password: welcome_123!
        driver-class-name: com.mysql.jdbc.Driver
        initialize: false
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:localhost}:8181/uaa/user
    client:
      client-id: acme
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

